apiVersion: v1
kind: Service
metadata:
  name: {{ include "zdm.fullname" . }}-frontend
  namespace: {{ include "zdm.namespace" . }}
  labels:
    {{- include "zdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "zdm.frontendSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
