{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zdm.fullname" . }}-backend
  namespace: {{ include "zdm.namespace" . }}
  labels:
    {{- include "zdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zdm.backendSelectorLabels" . | nindent 6 }}
{{- end }}
